#!/bin/sh


cd /tmp

if [ "$1" = "install" ]; then
  if [ "$2" = "" ]; then
    echo "install need parameter"
  else
    wget -Nq https://raw.github.com/nyaa/UbuntuScript/master/FirstInstall/$2.sh
    chmod +x $2.sh
    ./$2.sh
    rm $2.sh
  fi
elif  [ "$1" = "upgrade" ]; then
  cd /usr/bin/ && sudo wget -N https://raw.github.com/nyaa/UbuntuScript/master/apt-nyaa && sudo chmod +x apt-nyaa
elif  [ "$1" = "list" ]; then
    wget -Nq https://raw.github.com/nyaa/UbuntuScript/master/FirstInstall/list.txt
    echo "You can install:"
    cat list.txt
    rm list.txt
elif  [ "$1" = "search" ]; then
    wget -Nq https://raw.github.com/nyaa/UbuntuScript/master/FirstInstall/list.txt
    cat list.txt | grep $2
    rm list.txt
elif  [ "$1" = "help" ]; then
  echo "apt-nyaa ver 0.0.2\nUsage:\napt-nyaa install SOME_APP\napt-nyaa search SOMETHING\napt-nyaa list\napt-nyaa help\napt-nyaa upgrade"
else
  echo "$1: command not found"
fi
