set nocompatible
set noswapfile
set number      "show line numbers
set list "display tabs
set listchars=tab:▷⋅
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

syntax on

colorscheme solarized "https://github.com/altercation/vim-colors-solarized
if has("gui_running")
set guioptions-=T
set guioptions-=m
if has("gui_gtk2")
"set guifont=Courier\ New\ 13
set guifont=Inconsolata\ 12
elseif has("gui_photon")
set guifont=Courier\ New:s11
elseif has("gui_kde")
set guifont=Courier\ New/11/-1/5/50/0/0/0/1/0
elseif has("x11")
set guifont=-*-courier-medium-r-normal-*-*-180-*-*-m-*-*
else
set guifont=Monaco:h15
endif
set background=light
set cursorline
set lines=33
set columns=118
else
set background=dark
endif


" Statusline
set laststatus=2
set statusline=%F%m%r%h%w\ line:%l/%L[%p%%]


" Устанавливаем кодировки
set encoding=utf8
set termencoding=utf-8
" Включаем "умные" отспупы ( например, автоотступ после {)
set smartindent
"Настроим кол-во символов пробелов, которые будут заменять \t
set tabstop=2
set shiftwidth=2
set smarttab
set softtabstop=2
" Преобразование Таба в пробелы
set expandtab
"Включим автоотступы для новых строк
set ai
"Включим отступы в стиле Си
set cin
"Далее настроим поиск и подсветку результатов поиска и совпадения скобок
set showmatch 
set incsearch
set ignorecase
" Commenting blocks of code.
autocmd FileType c,cpp,java,scala let b:comment_leader = '// '
autocmd FileType sh,ruby,python,coffee   let b:comment_leader = '# '
autocmd FileType conf,fstab       let b:comment_leader = '# '
autocmd FileType tex              let b:comment_leader = '% '
autocmd FileType mail             let b:comment_leader = '> '
autocmd FileType vim              let b:comment_leader = '" '
noremap <silent> ,cc :<C-B>silent <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:nohlsearch<CR>
noremap <silent> ,cu :<C-B>silent <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:nohlsearch<CR>
