"Use Vim settings, rather then Vi settings (much better!).
"This must be first, because it changes other options as a side effect.
set nocompatible

set number      "show line numbers
"display tabs
set list
set listchars=tab:▷⋅

set incsearch   "find the next match as we type the search
set hlsearch    "hilight searches by default

set wrap        "dont wrap lines
set linebreak   "wrap lines at convenient points

syntax on

if has("gui_running")
  set guioptions-=T
  set guioptions-=m
  colorscheme desert 
  "set guifont=Courier\ 12
  set cursorline
  set lines=33
  set columns=118
else

endif

" Устанавливаем кодировки
set encoding=utf8
set termencoding=utf-8

" Включаем "умные" отспупы ( например, автоотступ после {)
set smartindent
"Настроим кол-во символов пробелов, которые будут заменять \t
set tabstop=2
set shiftwidth=2
set smarttab
set softtabstop=2
" Преобразование Таба в пробелы
set expandtab


"Включим автоотступы для новых строк
set ai
"Включим отступы в стиле Си
set cin

"Далее настроим поиск и подсветку результатов поиска и совпадения скобок
set showmatch 
set incsearch
set ignorecase

"-------------------------
" HOTKEYS
"-------------------------
" Launch program
map R <Esc>:w<CR>:!%:p<CR>

" Пробел в нормальном режиме перелистывает страницы
"nmap <Space> <PageDown>


" C-c and C-v - Copy/Paste в "глобальный клипборд"
vmap <C-C> "+yi
imap <C-V> <esc>"+gPi

" To save, ctrl-s.
nmap <c-s> :w<CR>
imap <c-s> <Esc>:w<CR>a


" F2 - save and exit
map <F2> :wq<cr>
vmap <F2> :wq<cr>i
imap <F2> :wq<cr>i

if has("gui_running")
  imap <F4> <Esc>:browse tabnew<CR> 
  map <F4> <Esc>:browse tabnew<CR>
  imap <F5> <Esc> :tabprev <CR>i
  map <F5> :tabprev <CR>
  imap <F6> <Esc> :tabnext <CR>i
  map <F6> :tabnext <CR>
  imap <F8> <Esc> :tabclose <CR>i
  map <F8> :tabclose <CR>
else
  map <F5> :bp<cr>
  vmap <F5> :bp<cr>
  imap <F5> :bp<cr>i
  map <F6> :bn<cr>
  vmap <F6> :bn<cr>
  imap <F6> :bn<cr>i
  map <F7> :ls<cr>
  vmap <F7> :ls<cr>
  imap <F7> :ls<cr>i
  map <F8> :bd<cr>
  vmap <F8> <esc>:bd<cr>
  imap <F8> <esc>:bd<cr>i
endif
