






"-------------------------
" HOTKEYS
"-------------------------

" To save, ctrl-s.
nmap <c-s> :w<CR>
imap <c-s> <Esc>:w<CR>a


" F2 - save
map <F2> :w<cr>

" F3 - save and exit
map <F3> :wq<cr>


