./archiveapps.sh
./chromium-codecs.sh
./brightness3820.sh
./bitcoin.sh
./streamripper.sh
./moc.sh
./dropbox.sh
./powertop.sh
./vlc.sh
./battery_status_widget.sh
./flash11.sh
./skype.sh
./cairodock.sh
./wuala.sh
./truecrypt.sh
./desktop.sh
./iperf.sh
./openssh-server.sh
./google-music.sh
./irssi.sh
./keepassx.sh
./git.sh
./screen.sh
./splashscreenoff.sh
./virtualbox.sh
./vim-gnome.sh
./openvpn.sh
./java6.sh
./xchat.sh
./gnome-mplayer.sh
